engineStrict: true

saveExact: true

catalog:
  effect: 4.0.0-rc.112
  typescript: 7.0.2

packages:
  - api
  - cli
  - mobile
  - packages/*

overrides:
  "@react-native/metro-config": 0.86.3

allowBuilds:
  esbuild: true
  msgpackr-extract: false
