engineStrict: true

saveExact: true

catalog:
  effect: 4.0.2
  typescript: 7.0.2

packages:
  - api
  - cli
  - mobile
  - packages/*

overrides:
  "@react-native/metro-config": 0.86.3

allowBuilds:
  dtrace-provider: true
  esbuild: true
  msgpackr-extract: false
  protobufjs: true

patchedDependencies:
  drizzle-orm@1.0.0-rc.5-5935859: patches/drizzle-orm@1.0.0-rc.5-5935859.patch

minimumReleaseAgeExclude:
  - "@effect/platform-node-shared@4.0.2"
  - "@effect/platform-node@4.0.2"
  - "@effect/sql-pg@4.0.2"
  - "@effect/sql-pglite@4.0.2"
  - "@effect/vitest@4.0.2"
  - effect@4.0.2
