import { useCSSVariable } from "uniwind";

// Runtime colors are defined in global.css and resolved here for native components.
export const useTheme = () => {
  const [
    background,
    backgroundElement,
    backgroundSelected,
    text,
    textSecondary,
    border,
    primary,
    primaryForeground,
    accentForeground,
    cardForeground,
    mutedForeground,
    popoverForeground,
    secondaryForeground,
    destructive,
    white,
    red500,
    gradientStart,
    gradientEnd,
  ] = useCSSVariable([
    "--color-background",
    "--color-background-element",
    "--color-background-selected",
    "--color-foreground",
    "--color-foreground-secondary",
    "--color-border",
    "--color-primary",
    "--color-primary-foreground",
    "--color-accent-foreground",
    "--color-card-foreground",
    "--color-muted-foreground",
    "--color-popover-foreground",
    "--color-secondary-foreground",
    "--color-destructive",
    "--color-white",
    "--color-red-500",
    "--qop-orange-light",
    "--qop-orange-dark",
  ]) as string[];

  return {
    accentForeground,
    background,
    backgroundElement,
    backgroundSelected,
    border,
    cardForeground,
    destructive,
    gradientEnd,
    gradientStart,
    mutedForeground,
    popoverForeground,
    primary,
    primaryForeground,
    red500,
    secondaryForeground,
    text,
    textSecondary,
    white,
  } as const;
};
