import "./globals.css";
import { Roboto_Mono } from "next/font/google";
import { cn } from "@/utils/cn";
import { Toaster } from "../components/ui/toaster";

const rm = Roboto_Mono({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          rm.className,
          "flex min-h-screen w-full items-center justify-center bg-orange-100"
        )}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
