import "./globals.css";

import { Roboto_Mono } from "next/font/google";

import Huddle01Provider from "@/components/Huddle01Provider";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/utils/cn";

const rm = Roboto_Mono({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          rm.className,
          "flex min-h-screen w-full items-center justify-center bg-orange-100"
        )}
      >
        <Huddle01Provider>{children}</Huddle01Provider>
        <Toaster />
      </body>
    </html>
  );
}
