[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
cache_path = "cache"
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 10_000
via_ir = true

[fuzz]
runs = 1_000

[invariant]
runs = 256
depth = 64
fail_on_revert = false
